name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      VENV_DIR: venv

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create virtual environment
      run: python -m venv $VENV_DIR

    - name: Upgrade pip and install dependencies
      run: |
        ./$VENV_DIR/bin/pip install --upgrade pip
        if [ -f requirements.txt ]; then
          ./$VENV_DIR/bin/pip install -r requirements.txt
        else
          ./$VENV_DIR/bin/pip install flask pytest
        fi

    - name: Run Tests
      run: ./$VENV_DIR/bin/python -m pytest test_app.py
